[package]
name = "wordy-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wordy"
path = "src/main.rs"

[dependencies]
gpui-kit.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wordy-doc = { path = "../wordy-doc" }
wordy-editor = { path = "../wordy-editor" }
wordy-index = { path = "../wordy-index" }
mime_guess = "2"
dirs.workspace = true
wordy-export = { path = "../wordy-export" }
